[project]
name = "remote-pt"
version = "0.1.0"
description = "Companies which offer full-time remote jobs with Portuguese contracts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "zensical>=0.0.15",
]
